/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'installation',
        'tokengeneration',
        'kafkaclients',
        'restapis',
        'streamclients',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description:
          "Let's learn about the most important Docusaurus concepts!",
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        'guides/docs/guides-kafkasecurity',
        'guides/docs/guides-kafkaclientsecurity',
        'guides/docs/guides-kafkarestproxy',
        {
          type: 'category',
          label: 'REST APIs',
          link: {
            type: 'doc',
            id: 'guides/docs/guides-kafkarestapis',
          },
          items: [
            'guides/docs/guides-kafkarestapis-authentication',
            'guides/docs/guides-kafkarestapis-producer',
            'guides/docs/guides-kafkarestapis-comsumer',
             {
               type: 'category',
               label: 'Sidebar',
               link: {
                 type: 'doc',
                 id: 'guides/docs/sidebar/index',
               },
               items: [
                 'guides/docs/sidebar/items',
                 'guides/docs/sidebar/autogenerated',
                 'guides/docs/sidebar/multiple-sidebars',
               ],
             },
          ],
        },
        {
          type: 'category',
          label: 'Stream clients',
          link: {
            type: 'doc',
            id: 'stream/stream-getstreamio',
          },
          items: [
            'stream/stream-chat',
            'stream/stream-videoaudio',
            'stream/stream-feeds',
          ],
        },
        {
          type: 'category',
          label: 'Markdown Features',
          link: {
            type: 'doc',
            id: 'guides/markdown-features/introduction',
          },
          items: [
            'guides/markdown-features/react',
            'guides/markdown-features/tabs',
            'guides/markdown-features/code-blocks',
            'guides/markdown-features/admonitions',
            'guides/markdown-features/toc',
            'guides/markdown-features/assets',
            'guides/markdown-features/links',
            'guides/markdown-features/plugins',
            'guides/markdown-features/math-equations',
            'guides/markdown-features/diagrams',
            'guides/markdown-features/head-metadata',
          ],
        },
        {
          type: 'category',
          label: 'Internationalization',
          link: {type: 'doc', id: 'i18n/introduction'},
          items: [
            {
              type: 'doc',
              id: 'i18n/tutorial',
              label: 'Tutorial',
            },
            {
              type: 'doc',
              id: 'i18n/git',
              label: 'Using Git',
            },
            {
              type: 'doc',
              id: 'i18n/crowdin',
              label: 'Using Crowdin',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Kaleidoscope',
      link: {type: 'doc', id: 'kaleidoscope/kaleidoscope'},
      items: [
        'kaleidoscope/kaleidoscope-chatgpt',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      link: {type: 'doc', id: 'advanced/index'},
      items: [
        'advanced/architecture',
        'advanced/plugins',
        'advanced/routing',
        'advanced/ssg',
        'advanced/client',
      ],
    },
  ],
  api: [
    'cli',
    'docusaurus-core',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
